//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "email_delivery_attempt")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub outbound_email_id: Uuid,
    pub attempt_number: i32,
    #[sea_orm(column_type = "Text")]
    pub provider_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub provider_message_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub attempt_status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub failure_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub failure_message: Option<String>,
    pub attempted_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub provider_response_snapshot: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::outbound_email::Entity",
        from = "Column::OutboundEmailId",
        to = "super::outbound_email::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    OutboundEmail,
}

impl Related<super::outbound_email::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OutboundEmail.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
