//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "outbound_email")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub dedupe_key: String,
    #[sea_orm(column_type = "Text")]
    pub email_kind: String,
    pub recipient_user_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub recipient_email: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub provider_message_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub provider_name: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub template_key: String,
    pub template_version: i32,
    #[sea_orm(column_type = "Text")]
    pub subject: String,
    #[sea_orm(column_type = "Text")]
    pub body_text: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub body_html: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub source_event_type: String,
    #[sea_orm(column_type = "Text")]
    pub source_event_id: String,
    pub source_occurred_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub send_status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error_message: Option<String>,
    pub next_attempt_after: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::email_delivery_attempt::Entity")]
    EmailDeliveryAttempt,
}

impl Related<super::email_delivery_attempt::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EmailDeliveryAttempt.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
