//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod outbox_event;
pub mod user_snapshot;
pub mod workspace;
pub mod workspace_channel;
pub mod workspace_invitation;
pub mod workspace_invite_link;
pub mod workspace_member;
pub mod workspace_member_role;
pub mod workspace_role;
