//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::outbox_event::Entity as OutboxEvent;
pub use super::user_snapshot::Entity as UserSnapshot;
pub use super::workspace::Entity as Workspace;
pub use super::workspace_channel::Entity as WorkspaceChannel;
pub use super::workspace_invitation::Entity as WorkspaceInvitation;
pub use super::workspace_invite_link::Entity as WorkspaceInviteLink;
pub use super::workspace_member::Entity as WorkspaceMember;
pub use super::workspace_member_role::Entity as WorkspaceMemberRole;
pub use super::workspace_role::Entity as WorkspaceRole;
