//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user_snapshot")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,
    pub email_verified: bool,
    #[sea_orm(column_type = "Text")]
    pub username: String,
    #[sea_orm(column_type = "Text")]
    pub display_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub avatar_url: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::workspace::Entity")]
    Workspace,
    #[sea_orm(has_many = "super::workspace_channel::Entity")]
    WorkspaceChannel,
    #[sea_orm(has_many = "super::workspace_invite_link::Entity")]
    WorkspaceInviteLink,
}

impl Related<super::workspace::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workspace.def()
    }
}

impl Related<super::workspace_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceChannel.def()
    }
}

impl Related<super::workspace_invite_link::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceInviteLink.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
