//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "workspace_member")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub workspace_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub membership_status: String,
    pub joined_at: DateTimeWithTimeZone,
    pub removed_at: Option<DateTimeWithTimeZone>,
    pub added_by_user_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_snapshot::Entity",
        from = "Column::AddedByUserId",
        to = "super::user_snapshot::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserSnapshot2,
    #[sea_orm(
        belongs_to = "super::user_snapshot::Entity",
        from = "Column::UserId",
        to = "super::user_snapshot::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserSnapshot1,
    #[sea_orm(
        belongs_to = "super::workspace::Entity",
        from = "Column::WorkspaceId",
        to = "super::workspace::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Workspace,
}

impl Related<super::workspace::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workspace.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
