//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "workspace")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub owner_user_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub icon_url: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub archived_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::workspace_channel::Entity")]
    WorkspaceChannel,
    #[sea_orm(has_many = "super::workspace_invitation::Entity")]
    WorkspaceInvitation,
    #[sea_orm(has_many = "super::workspace_invite_link::Entity")]
    WorkspaceInviteLink,
    #[sea_orm(has_many = "super::workspace_member::Entity")]
    WorkspaceMember,
    #[sea_orm(has_many = "super::workspace_member_role::Entity")]
    WorkspaceMemberRole,
    #[sea_orm(has_many = "super::workspace_role::Entity")]
    WorkspaceRole,
}

impl Related<super::workspace_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceChannel.def()
    }
}

impl Related<super::workspace_invitation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceInvitation.def()
    }
}

impl Related<super::workspace_invite_link::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceInviteLink.def()
    }
}

impl Related<super::workspace_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceMember.def()
    }
}

impl Related<super::workspace_member_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceMemberRole.def()
    }
}

impl Related<super::workspace_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceRole.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
