//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "workspace_invite_link")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub workspace_id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub code: String,
    pub created_by_user_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub expires_at: Option<DateTimeWithTimeZone>,
    pub max_uses: Option<i32>,
    pub use_count: i32,
    pub created_at: DateTimeWithTimeZone,
    pub revoked_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_snapshot::Entity",
        from = "Column::CreatedByUserId",
        to = "super::user_snapshot::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserSnapshot,
    #[sea_orm(
        belongs_to = "super::workspace::Entity",
        from = "Column::WorkspaceId",
        to = "super::workspace::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Workspace,
}

impl Related<super::user_snapshot::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSnapshot.def()
    }
}

impl Related<super::workspace::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workspace.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
