//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "workspace_role")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "name")]
    pub workspace_id: Uuid,
    #[sea_orm(column_type = "Text", unique_key = "name")]
    pub name: String,
    pub permissions: i32,
    pub is_system_role: bool,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::workspace::Entity",
        from = "Column::WorkspaceId",
        to = "super::workspace::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Workspace,
    #[sea_orm(has_many = "super::workspace_member_role::Entity")]
    WorkspaceMemberRole,
}

impl Related<super::workspace::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workspace.def()
    }
}

impl Related<super::workspace_member_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceMemberRole.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
