//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "friendship_edge")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub friend_user_id: Uuid,
    pub request_id: Uuid,
    pub accepted_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::friend_request::Entity",
        from = "Column::RequestId",
        to = "super::friend_request::Column::RequestId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    FriendRequest,
    #[sea_orm(
        belongs_to = "super::user_snapshot::Entity",
        from = "Column::FriendUserId",
        to = "super::user_snapshot::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserSnapshot2,
    #[sea_orm(
        belongs_to = "super::user_snapshot::Entity",
        from = "Column::UserId",
        to = "super::user_snapshot::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserSnapshot1,
}

impl Related<super::friend_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FriendRequest.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
