//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "friend_request")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub request_id: Uuid,
    pub requester_user_id: Uuid,
    pub addressee_user_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub resolved_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub resolution_reason: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::friendship_edge::Entity")]
    FriendshipEdge,
    #[sea_orm(
        belongs_to = "super::user_snapshot::Entity",
        from = "Column::AddresseeUserId",
        to = "super::user_snapshot::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserSnapshot2,
    #[sea_orm(
        belongs_to = "super::user_snapshot::Entity",
        from = "Column::RequesterUserId",
        to = "super::user_snapshot::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserSnapshot1,
}

impl Related<super::friendship_edge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FriendshipEdge.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
