//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::friend_request::Entity as FriendRequest;
pub use super::friendship_edge::Entity as FriendshipEdge;
pub use super::outbox_event::Entity as OutboxEvent;
pub use super::user_block::Entity as UserBlock;
