//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::friend_request::Entity as FriendRequest;
pub use super::friendship_edge::Entity as FriendshipEdge;
pub use super::outbox_event::Entity as OutboxEvent;
pub use super::user_block::Entity as UserBlock;
pub use super::user_snapshot::Entity as UserSnapshot;
