//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user_block")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub blocker_user_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub blocked_user_id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub reason: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_snapshot::Entity",
        from = "Column::BlockedUserId",
        to = "super::user_snapshot::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserSnapshot2,
    #[sea_orm(
        belongs_to = "super::user_snapshot::Entity",
        from = "Column::BlockerUserId",
        to = "super::user_snapshot::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserSnapshot1,
}

impl ActiveModelBehavior for ActiveModel {}
