apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: bootstrap-ext-auth
  namespace: relay
  labels:
    app.kubernetes.io/name: bootstrap
    app.kubernetes.io/part-of: relay
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: GRPCRoute
      name: bootstrap-grpc
  extAuth:
    grpc:
      backendRefs:
        - name: identity
          port: 50051
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: chat-ext-auth
  namespace: relay
  labels:
    app.kubernetes.io/name: chat
    app.kubernetes.io/part-of: relay
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: GRPCRoute
      name: chat-grpc
  extAuth:
    grpc:
      backendRefs:
        - name: identity
          port: 50051
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: workspace-ext-auth
  namespace: relay
  labels:
    app.kubernetes.io/name: workspace
    app.kubernetes.io/part-of: relay
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: GRPCRoute
      name: workspace-grpc
  extAuth:
    grpc:
      backendRefs:
        - name: identity
          port: 50051
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: friendship-ext-auth
  namespace: relay
  labels:
    app.kubernetes.io/name: friendship
    app.kubernetes.io/part-of: relay
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: GRPCRoute
      name: friendship-grpc
  extAuth:
    grpc:
      backendRefs:
        - name: identity
          port: 50051
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: realtime-ext-auth
  namespace: relay
  labels:
    app.kubernetes.io/name: realtime
    app.kubernetes.io/part-of: relay
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: realtime-websocket
  extAuth:
    grpc:
      backendRefs:
        - name: identity
          port: 50051
