apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: relay-envoy-local
  labels:
    app.kubernetes.io/name: envoy-gateway
    app.kubernetes.io/part-of: relay
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: relay-gateway
  namespace: relay-system
  labels:
    app.kubernetes.io/name: envoy-gateway
    app.kubernetes.io/part-of: relay
spec:
  gatewayClassName: relay-envoy-local
  listeners:
    - name: grpc
      protocol: HTTP
      port: 8080
      allowedRoutes:
        namespaces:
          from: Same
