apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: identity
  namespace: relay-system
  labels:
    app.kubernetes.io/name: envoy-gateway
    app.kubernetes.io/part-of: relay
spec:
  parentRefs:
    - name: relay-gateway
  hostnames:
    - identity.local
  rules:
    - backendRefs:
        - name: identity
          port: 50051
