apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-smoke
  namespace: relay-system
  labels:
    app.kubernetes.io/name: envoy-gateway
    app.kubernetes.io/part-of: relay
    app.kubernetes.io/component: grpc-smoke
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: grpc-smoke
  template:
    metadata:
      labels:
        app.kubernetes.io/name: envoy-gateway
        app.kubernetes.io/part-of: relay
        app.kubernetes.io/component: grpc-smoke
    spec:
      containers:
        - name: yages
          image: ghcr.io/projectcontour/yages:v0.1.0
          ports:
            - containerPort: 9000
              name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-smoke
  namespace: relay-system
  labels:
    app.kubernetes.io/name: envoy-gateway
    app.kubernetes.io/part-of: relay
    app.kubernetes.io/component: grpc-smoke
spec:
  selector:
    app.kubernetes.io/component: grpc-smoke
  ports:
    - name: grpc
      port: 9000
      targetPort: 9000
      protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: grpc-smoke
  namespace: relay-system
  labels:
    app.kubernetes.io/name: envoy-gateway
    app.kubernetes.io/part-of: relay
    app.kubernetes.io/component: grpc-smoke
spec:
  parentRefs:
    - name: relay-gateway
  rules:
    - matches:
        - method:
            type: Exact
            service: grpc.reflection.v1alpha.ServerReflection
            method: ServerReflectionInfo
        - method:
            type: Exact
            service: yages.Echo
            method: Ping
      backendRefs:
        - name: grpc-smoke
          port: 9000
