//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "conversation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub target_type: String,
    #[sea_orm(unique)]
    pub dm_pair_id: Option<Uuid>,
    #[sea_orm(unique)]
    pub workspace_channel_id: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::chat_message::Entity")]
    ChatMessage,
    #[sea_orm(
        belongs_to = "super::dm_pair::Entity",
        from = "Column::DmPairId",
        to = "super::dm_pair::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    DmPair,
}

impl Related<super::chat_message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatMessage.def()
    }
}

impl Related<super::dm_pair::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DmPair.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
