//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_account")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub email: String,
    #[sea_orm(column_type = "Text", unique)]
    pub email_normalized: String,
    pub email_verified_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub account_status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::email_verification_token::Entity")]
    EmailVerificationToken,
    #[sea_orm(has_one = "super::user_credential_password::Entity")]
    UserCredentialPassword,
    #[sea_orm(has_one = "super::user_profile::Entity")]
    UserProfile,
    #[sea_orm(has_many = "super::user_session::Entity")]
    UserSession,
}

impl Related<super::email_verification_token::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EmailVerificationToken.def()
    }
}

impl Related<super::user_credential_password::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserCredentialPassword.def()
    }
}

impl Related<super::user_profile::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserProfile.def()
    }
}

impl Related<super::user_session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSession.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
