//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "compose_queue")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub compose_key: String,
    #[sea_orm(column_type = "Text")]
    pub compose_kind: String,
    pub user_id: Option<Uuid>,
    pub workspace_id: Option<Uuid>,
    pub channel_id: Option<Uuid>,
    pub conversation_id: Option<Uuid>,
    pub dm_pair_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub attempts: i32,
    pub available_at: DateTimeWithTimeZone,
    pub claimed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
