//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "dm_projection")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,
    pub conversation_id: Option<Uuid>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub dm_pair_id: Uuid,
    pub peer_user_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub peer_username: String,
    #[sea_orm(column_type = "Text")]
    pub peer_display_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub peer_avatar_url: Option<String>,
    pub last_message_seq: Option<i64>,
    pub last_read_conversation_message_seq: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_message_preview: Option<String>,
    pub last_activity_at: Option<DateTimeWithTimeZone>,
    pub unread_count: i32,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
