//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "friend_request_snapshot")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub friend_request_id: Uuid,
    pub requester_user_id: Uuid,
    pub addressee_user_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
