//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod compose_queue;
pub mod conversation_message_state;
pub mod conversation_read_state;
pub mod conversation_snapshot;
pub mod dm_pair_snapshot;
pub mod dm_projection;
pub mod dm_unread_projection;
pub mod friend_request_snapshot;
pub mod processed_event;
pub mod user_app_projection;
pub mod user_snapshot;
pub mod workspace_channel_projection;
pub mod workspace_channel_snapshot;
pub mod workspace_channel_unread_projection;
pub mod workspace_member_snapshot;
pub mod workspace_projection;
pub mod workspace_snapshot;
pub mod workspace_unread_projection;
